### ISSUE TITLE
font sizes

### ISSUE THREAD

**Issue by kevinsimper** [jdan/cleaver#104]
h1 is 300%
h2 is 100%

Shouldn't that be a little more similar?

**Comment by jdan** [comment]
The reason is because I use `h2` as a subtitle on intro slides, and `h3` as a slide title. We could probably reverse them :) Or just have slides have their own `h1`.

**Comment by sjaakvandenberg** [comment]
You can also set an h1 size of 150% or so, and then for the first slide to use a bigger h1 size:

```css
#slide-1 h1 {
    font-size: 300%;
}
```

**Comment by firstdoit** [comment]
This is easy to modify on your own theme. Otherwise, PR welcome.
