### ISSUE TITLE
Can I export the Cleaver presentation into an PDF format presentation?

### ISSUE THREAD

**Issue by csrgxtu** [jdan/cleaver#116]
The html presentation is beautiful, can i export the presentation into PDF format?

**Comment by sudodoki** [comment]
Yes, you can if you do 'Print as PDF' - it requires corresponding 'media print' styles in the theme.

**Comment by jdan** [comment]
Thanks @sudodoki :)

@csrgxtu Does this work for you?

**Comment by adriens** [comment]
Hi guys, i also have a beautiful html presentation... but could not succeed in getting a landscape pdf output ('im usin sudodoki/reveal-cleaver-theme)
Any idea on which theme i should use to get that properly done ?

Target goal : export as PDF t push it to slideshare ;-p

**Comment by jdan** [comment]
@adriens try copying the `@media print { }` section from [default.css](https://github.com/jdan/cleaver/blob/master/resources/default.css#L200-L249)

**Comment by adriens** [comment]
Thanks jdan : i'll give it a try and let you know.

**Comment by jcmmen3a84e645** [comment]
`+1` to export to pdf (even using chrome)

**Comment by adriens** [comment]
Hi guys : does anyone know which theme natively supports 'media print' ?

**Comment by firstdoit** [comment]
@adriens I guess the default one does

**Comment by iliocatallo** [comment]
Any news on this side?

**Comment by firstdoit** [comment]
Remember: PR's are welcome.
