### ISSUE TITLE
Markdown render issue?

### ISSUE THREAD

**Issue by sudodoki** [jdan/cleaver#117]
```
0. A
1. B
2. C
```

will yield markup for items `1.` & `2.` only.

**Comment by sudodoki** [comment]
cleaver version 0.7.2

**Comment by djyde** [comment]
You may need to change your rendered html `<ol>` to  `<ol start='0'>`

**Comment by jdan** [comment]
I guess this is due to whatever markdown parser we are using, in which case it might be a bug on their end.

**Comment by sudodoki** [comment]
This no longer the case for 0.8.2. 🎉
