### ISSUE TITLE
unidentified alias "*Pssst**:"

### ISSUE THREAD

**Issue by hongqi** [jdan/cleaver#118]
!! JS-YAML: unidentified alias "*Pssst**:" at line 3, column 11:
    **Pssst**: Did you know the wiki [has its  ...

**Comment by jdan** [comment]
Hi, can you paste your slideshow code please?

**Comment by hongqi** [comment]
i do this:
$: cleaver options.md 
at path node_modules/cleaver/docs

**Comment by jdan** [comment]
`options.md` is just a markdown file, it's not meant to be a presentation :)

As such, cleaver won't be able to parse it.
