### ISSUE TITLE
how to write vertical sliders with Markdown?

### ISSUE THREAD

**Issue by mushaofeng** [jdan/cleaver#121]
how to write vertical sliders with Markdown?

**Comment by jdan** [comment]
Mind clarifying?



--



jordan scales

http://jordanscales.com

**Comment by mushaofeng** [comment]
how to wrtie with markdown
```
        <section>
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
```

**Comment by jdan** [comment]
Slides don't really have any direction, and we just swap them out so the user never sees things moving up/down or left/right.

You can control the slides with either the left and right arrow keys or up and down.

If you're looking for something like reveal.js's, vertical slides, you unfortunately won't find that functionality here, sorry!

**Comment by gabeboning** [comment]
@jdan is that because it just hasn't been written, or you have no interest in it becoming part of the project?

I don't see "vertical slides" as something that makes sense, but there are times I've wanted an easy way to do an incremental reveal of list items or something like that.

**Comment by jdan** [comment]
I feel it adds a lot of unnecessary complexity. The current solution is to just make a few slides for an incremental reveal, but I've been theorizing ways to add pre-processing to cleaver.




It needs a lot of love :)



--



jordan scales

http://jordanscales.com
