### ISSUE TITLE
Not working well for higher resolution screens

### ISSUE THREAD

**Issue by BernhardPosselt** [jdan/cleaver#125]
Hi, I'm working on a presentation for a monitor connected via HDMI and full HD

The limitation in the default style to 800x600 makes the content very hard to read. 

Maybe add a config option to set the desired presentation resolution?

**Comment by sudodoki** [comment]
I would suggest just creating 'widescreen' theme or something, based on standard one.

**Comment by jdan** [comment]
@BernhardPosselt current solution is to just zoom (command/control +/-). Other solution is to make your own stylesheet with a bigger width and height as needed.

I'm going to close this issue, but if you have any further ideas please let me know and we can explore them!

**Comment by BernhardPosselt** [comment]
I've switched to using one of the bundled themes which works fine. The default theme is just a bit broken IMHO :)
