### ISSUE TITLE
Feature: add built-in server

### ISSUE THREAD

**Issue by neelabhg** [jdan/cleaver#127]
This is a great tool! I was really short of time before I had to make a presentation, and this is the only tool which allowed me to start and build a presentation quickly without reading much documentation. Thank you!

I have a feature suggestion.

When using local file URLs, Chrome (Version 46.0.2490.80 m) throws this:
`Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///...html' cannot be created in a document with origin 'null'.`

Because of this, location hashes in the address bar do not update when navigating slides, causing a poor presentation development experience (after every reload, the slideshow starts from the beginning).

Serving the HTML file through a server will solve this issue. A live-reloading server will also help in implementing #88.

I've been using [http-server](https://www.npmjs.com/package/http-server) so far, but something like `cleaver serve` would be great. It will build and serve files automatically.

**Comment by firstdoit** [comment]
I feel this lays outside of the scope of cleaver.
Simply `npm i -g http-server; http-server` and you're all set.

As an aside, the next version will fallback to `window.location` to avoid this problem :+1:
