### ISSUE TITLE
Feature: support for overriding the credits template

### ISSUE THREAD

**Issue by neelabhg** [jdan/cleaver#129]
It is currently possible to override the templates used for rendering the slides and the whole slideshow  in the options (using the [`template`](https://github.com/jdan/cleaver/blob/master/docs/options.md#template) and [`layout`](https://github.com/jdan/cleaver/blob/master/docs/options.md#layout) options respectively) as well as in themes (using `template.mustache` and `layout.mustache` files respectively).

It would be great to provide support for overriding the template used for the "credits" slide. A `template` field could be added to the [`author`](https://github.com/jdan/cleaver/blob/master/docs/options.md#author) option, and themes could provide a file like `credits.mustache`.

My use case for this is to add a profile picture, format the website URL, etc. The current default template could also be updated to add these things, but support for overriding this template would still be useful.

**Comment by sudodoki** [comment]
One solution would be omitting author option altogether and providing your own last slide either with markdown or html.
Functionality as you described would require [code change](https://github.com/jdan/cleaver/pull/166).

**Comment by sudodoki** [comment]
I forgot about this issue when I closed https://github.com/jdan/cleaver/pull/166#issuecomment-348776942. I think if you credits slides is really that different from other slides it makes sense. Otherwise you might just stick to omitting author & putting same think via plain markdown in the presentation itself. 🤔

**Comment by neelabhg** [comment]
Thanks for trying out the code change. I understand your reasoning that the feature is not critical and has a workaround, so I'm closing the issue. I'll re-open if I really need this feature.
