### ISSUE TITLE
how to use cleaver in express?

### ISSUE THREAD

**Issue by CarlosRen** [jdan/cleaver#131]
how can i use the cleaver in  Express as module?

**Comment by jdan** [comment]
Hey @CarlosRen,

Cleaver typically runs as a standalone program (from the command-line), though there is nothing stopping you from using it's undocumented API!

[Look at `bin/cleaver` for inspiration](https://github.com/jdan/cleaver/blob/master/bin/cleaver):

```js
 var presentation = new Cleaver(contents, options, path.resolve(path.dirname(file)));
presentation.run()
    .then(function (product) {
        var outputFile = presentation.options.output || path.basename(file, '.md') + '-cleaver.html';
        fs.writeFile(outputFile, product);
    })
    .fail(function (err) {
        process.stderr.write('!! ' + err.message + '\n');
        if (program.debug) {
            process.stderr.write(err.stack);
        }
        process.exit(1);
    });
```

Does that sort of make sense? I'd love to help you get something working.
