### ISSUE TITLE
How do you upgrade cleaver ?

### ISSUE THREAD

**Issue by adriens** [jdan/cleaver#134]
HI don't find on the README how to upgrade cleaver to its latest version. As i see the latest release, i'd like to upgrade to it ;-p

Thank you in advance for your help.

Regards,

Adrien

**Comment by jdan** [comment]
Hey @adriens,

```
npm update -g cleaver
```

Should do the trick! Let me know if you run into any problems.

**Comment by adriens** [comment]
it does perfectly the job :+1:  :+1:  :+1:  see below :

➜  ~  sudo npm update -g cleaver
[sudo] password for salad74: 
npm http GET https://registry.npmjs.org/cleaver
npm http 200 https://registry.npmjs.org/cleaver
npm http GET https://registry.npmjs.org/cleaver/-/cleaver-0.7.5.tgz
npm http 200 https://registry.npmjs.org/cleaver/-/cleaver-0.7.5.tgz
npm http GET https://registry.npmjs.org/cleaver/0.7.5
npm http 200 https://registry.npmjs.org/cleaver/0.7.5
npm http GET https://registry.npmjs.org/cleaver/-/cleaver-0.7.5.tgz
npm http 200 https://registry.npmjs.org/cleaver/-/cleaver-0.7.5.tgz
npm http GET https://registry.npmjs.org/js-yaml/2.1.0
npm http GET https://registry.npmjs.org/highlight.js
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/q/0.9.6
npm http GET https://registry.npmjs.org/mustache/0.7.0
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/js-yaml/2.1.0
npm http GET https://registry.npmjs.org/js-yaml/-/js-yaml-2.1.0.tgz
npm http 200 https://registry.npmjs.org/js-yaml/-/js-yaml-2.1.0.tgz
npm http 200 https://registry.npmjs.org/mustache/0.7.0
npm http GET https://registry.npmjs.org/mustache/-/mustache-0.7.0.tgz
npm http 200 https://registry.npmjs.org/q/0.9.6
npm http GET https://registry.npmjs.org/q/-/q-0.9.6.tgz
npm http 200 https://registry.npmjs.org/highlight.js
npm http GET https://registry.npmjs.org/highlight.js/-/highlight.js-9.0.0.tgz
npm http 200 https://registry.npmjs.org/q/-/q-0.9.6.tgz
npm http 200 https://registry.npmjs.org/marked
npm http 200 https://registry.npmjs.org/highlight.js/-/highlight.js-9.0.0.tgz
npm http 200 https://registry.npmjs.org/mustache/-/mustache-0.7.0.tgz
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 304 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore.string
/usr/local/bin/cleaver -> /usr/local/lib/node_modules/cleaver/bin/cleaver
cleaver@0.7.5 /usr/local/lib/node_modules/cleaver
├── commander@2.1.0
├── marked@0.2.10
├── q@0.9.6
├── mustache@0.7.0
├── highlight.js@9.0.0
├── debug@2.2.0 (ms@0.7.1)
└── js-yaml@2.1.0 (esprima@1.0.4, argparse@0.1.16)
➜  ~  cleaver version
0.7.5
➜  ~

**Comment by jdan** [comment]
Woot!

**Comment by adriens** [comment]
just made PR ;-p
