### ISSUE TITLE
on each first launch of the day, check of new version is available

### ISSUE THREAD

**Issue by adriens** [jdan/cleaver#137]
Like on Oh My Zsh, when lauching cleaver, check if a newer version is available.

**Comment by jdan** [comment]
I'm thinking a good plan of action here could be to add a `cleaver update` command and automatically run that as you suggested.

**Comment by adriens** [comment]
:+1:  for your idea !

**Comment by firstdoit** [comment]
NPM already offers a command for this: 
`npm view cleaver version`

Closing for now, feel free to reopen.
