### ISSUE TITLE
tag suffix cannot contain flow indicator chracters at line x

### ISSUE THREAD

**Issue by joelstransky** [jdan/cleaver#138]
Trying to include a valid MD image and JS-YAML absolutely wont have it.

` ![image alt](path/to/image.jpg)`

**Comment by jdan** [comment]
Hey @joelstransky,

Mind posting the markdown you're trying to use with cleaver? Thanks!

**Comment by joelstransky** [comment]
`![](http://i2.wp.com/wptavern.com/wp-content/uploads/2015/02/sage.jpg)`

**Comment by jdan** [comment]
My apologies I meant the entire document :) I'm able to use images just fine in my test file.

**Comment by joelstransky** [comment]
It appears my issue was a result of not including the options block followed by a `--`
was getting the error 
`!! JS-YAML: tag suffix cannot contain flow indicator characters at line 2, column 71:
     ... ontent/uploads/2015/02/sage.jpg)
                                         ^`

**Comment by jdan** [comment]
@joelstransky Yep! I'd like to eventually remove `--` all together: it seems pretty straightforward to separate options from the content, but splitting slides might be tricky! (maybe `# Title`?)

All good now?

**Comment by joelstransky** [comment]
Yep, working fine. Sorry about the false issue.

**Comment by jdan** [comment]
No worries! Be sure to let me know if you run into anything else. Have fun poking around :)

**Comment by DavidWaza** [comment]
Hello i am trying to map img src from markdown but my image is not displaying
`date: "2022-04-17"
---
![src]: `(https://res.cloudinary.com/ddwkojhaj/image/upload/f_auto,q_auto/v1678367301/pexels-cottonbro-studio-5990270_ewl94m.jpg);
