### ISSUE TITLE
Syntax highlighting doesn't work sometimes

### ISSUE THREAD

**Issue by mike-ward** [jdan/cleaver#139]
Cleaver does not syntax highlight the following:

```xml
<todo>
  <h3>{ opts.title }</h3>

  <ul>
    <li each="{ item, i in items }>"{ item }</li>
  </ul>

  <form onsubmit="{ add }">
    <input>
    <button>Add #{ items.length + 1 }</button>
  </form>

  <style scoped>
    h3 { font-size: 14px; }
  </style>

  <script>
    this.items = []

    add(e) {
      var input = e.target[0]
      this.items.push(input.value)
      input.value = ''
    }
  </script>
</todo>
```

See http://mike-ward.net/talk-riotjs/#3 for reference.

**Comment by jdan** [comment]
Hey @mike-ward,

Looks like [highlight.js](https://highlightjs.org/) doesn't support XML: http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html

How does HTML look?

**Comment by mike-ward** [comment]
Same result. Note, slide http://mike-ward.net/talk-riotjs/#12 is decorated with the `XML` tag and does highight.

**Comment by mike-ward** [comment]
Found if I change the to `js` it highlights the code. Weird, but acceptable.
