### ISSUE TITLE
Watch exits on error

### ISSUE THREAD

**Issue by mike-ward** [jdan/cleaver#142]
![image](https://cloud.githubusercontent.com/assets/567927/11997545/746e9ffe-aa4c-11e5-87f3-c71e9363b8d8.png)

Watch exits when an error is encounted. In this case my script block was

```
```j
```

instead of

```
```js
```

**Comment by jdan** [comment]
Fixed via cf79c02d17abb20540405bce175a003b729d4f19! Thanks for reporting this one, @mike-ward :)

**Comment by jdan** [comment]
Go ahead and update to 0.7.7 `npm update -g cleaver`

**Comment by mike-ward** [comment]
I can confirm the fix works Thanks!

**Comment by jdan** [comment]
:+1: Glad to hear it!
