### ISSUE TITLE
Add class to Author/About slide

### ISSUE THREAD

**Issue by mike-ward** [jdan/cleaver#143]
It would be helpful if the last slide (the about author slide) had a class (like `about-author`). That way the slide could be styled. Currently, I have to reference the slide number to do this.

Being able to construct slides in markdown and post them on github just rocks by the way...

**Comment by jdan** [comment]
Great idea @mike-ward :) And thank you very much for the high compliment!

**Comment by firstdoit** [comment]
@mike-ward PR welcome :)

**Comment by elstamey** [comment]
There are no open PRs.  Is this being added?

**Comment by jdan** [comment]
Hi @elstamey,

Looks like this was added in #146 and is available in cleaver version 0.8.2!

Is it working for you?
