### ISSUE TITLE
Slide overview

### ISSUE THREAD

**Issue by select** [jdan/cleaver#149]
Hi there, I created a theme where you can get a slide overview with the ESC key. Are you interested to have this in your default theme?

If yes I could prepare the code. ... might need a while though.

Here is the theme
https://github.com/select/cleaver-select-theme

**Comment by jdan** [comment]
Hey @select.

Might be better to keep it in a theme just as you did. Thanks for adding it to the wiki. If we end up wanting that functionality I'll be sure to ping you.

**Comment by jdan** [comment]
*Very* cool by the way.

**Comment by select** [comment]
Thanks :D

**Comment by select** [comment]
@jdan I also added fragment support to the theme, just wanted to let you know
