### ISSUE TITLE
Need to create an empty settings.json for local themes

### ISSUE THREAD

**Issue by lrq3000** [jdan/cleaver#150]
Not sure if this is intended or not, but cleaver requires a `settings.json` file to exist for local themes but not for remote theme. In the documentation, it is said that normally cleaver should only read available config files.

See https://github.com/sudodoki/reveal-cleaver-theme/issues/6 .

**Comment by sudodoki** [comment]
Might be related to #147

**Comment by sudodoki** [comment]
So, original issue from sudodoki/reveal-cleaver-theme is fixed, and I would just close this and track this in #147
