### ISSUE TITLE
Helper links: 404

### ISSUE THREAD

**Issue by coloradokim** [jdan/cleaver#157]
![image](https://cloud.githubusercontent.com/assets/10536053/17156696/5cf1eb88-5348-11e6-93c8-62ad89382a8f.png)

**Comment by sudodoki** [comment]
@coloradokim there're no such files in that theme. Does it yield incorrect/broken presentation? Otherwise would consider this non-issue.

**Comment by sudodoki** [comment]
Considering this non-issue. In case something is still not quite right, let us know.
