### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by fpetrone** [jdan/cleaver#158]
Im a newbie and Im trying to use cleaver. I got the following error and I cant find the solution, could someone please give me some hint? Thx!  

ERROR: cleaver loaded templates +0ms
!!JS-YAML: end of the stream or a document separator us expected at line 3, column 19: 
<head prefix="og: http://ogp.me/ns#  fb: http//o..."

**Comment by sudodoki** [comment]
can you share markdown code you are trying to convert?

**Comment by fpetrone** [comment]
Sorry,  It was some nodejs instalation issue. Everything works fine now. Thanks for cleaver, it is very helpful 👍

**Comment by jdan** [comment]
Glad to hear it @fpetrone :) Be sure to let us know if you need anything else!
