### ISSUE TITLE
Update some dependencies

### ISSUE THREAD

**Issue by sudodoki** [jdan/cleaver#173]
Just to please bithound god and maybe because it might fix some non-reported issues (and supposedly, at some point get marked that plays nicely with math):
+ mustache
+ marked
Optionally, jshint

**Comment by sapegin** [comment]
GitHub also shows a warning now:

![image 2017-11-29 at 8 53 30 am](https://user-images.githubusercontent.com/70067/33364763-1a1a884e-d4e6-11e7-93bd-36736074d591.png)

**Comment by sudodoki** [comment]
Done via https://github.com/jdan/cleaver/commit/c386e53369e2ab3a1fdd4a15483588455a9e2597
