### ISSUE TITLE
Print layout?

### ISSUE THREAD

**Issue by bebraw** [jdan/cleaver#18]
It would be useful to have proper print layout available. This would make it easy to export the slides in PDF format (useful for sharing).

**Comment by neotheicebird** [comment]
Adding the following metadata and generating a presentation, generates a html with content `[object][object]`

How to print a slideshow into a PDF?
metadata:
    title: Print Layout Example
    output: print.html
    template: /absolute/path/to/print.mustache

**Comment by jdan** [comment]
Hi @neotheicebird,

Not sure I understand your question. Is metadata blank? Can you be more specific?

**Comment by neotheicebird** [comment]
@jdan , I want to make my presentation into pdf. I just changed the metadata of the .md file am working on with something like what you have told above. Then I run `cleaver` over it. The `print.html` generated has content `[object][object]`. How do I convert this file into a PDF presentation, if it is possible? Thanks.

**Comment by bebraw** [comment]
@neotheicebird The idea with print CSS is that you can print the file to a PDF. Just try to print the HTML regularly but output to PDF file instead of printer. Alternatively you could try to explore a tool like [pandoc](http://johnmacfarlane.net/pandoc/) if you are not comfortable printing through a browser.

**Comment by neotheicebird** [comment]
great. Thanks for the help @bebraw. Let me try these options out and get back.

**Comment by twilson63** [comment]
I used this template and it worked great for me:

``` mustache
{{#slides}}
  <div class="nohide" id="slide-{{id}}">
    <section class="slide-content">{{{content}}}</section>
  </div>
{{/slides}}
```
