### ISSUE TITLE
Error when trying the example

### ISSUE THREAD

**Issue by Bartvds** [jdan/cleaver#22]
If I copy the basic.md example from the view-raw and paste it in a new .md file and run it in `cleaver` I get this error:

```
YAMLException: JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 10, column 1:
    # Cleaver 101
    ^
```

This is cleaver 0.2.0 from npm, on Windows Vista 64 using Node v0.10.17

**Comment by faxiubite** [comment]
maybe it‘s the issue of "blank space", 
![image](https://cloud.githubusercontent.com/assets/3492597/19235070/f56d2c00-8f21-11e6-8b4a-b1e2928d3912.png)

check the yml
