### ISSUE TITLE
Speaker notes?

### ISSUE THREAD

**Issue by dannguyen** [jdan/cleaver#69]
Is there anyway to set up a block in which freeform Markdown text can be added, so that in slideshow form, the text is hidden, but can be visible as HTML/Markdown when viewed on Github (or similar Markdown setup)?

**Comment by Stolzenhain** [comment]
Was about to propose [footnote](https://michelf.ca/projects/php-markdown/extra/#footnotes) annotations when I just stumbled about how [Deckset](http://www.decksetapp.com/) handles it: 

[with carets (`^`)](http://www.decksetapp.com/cheatsheet/#presenter-notes), which would be close to footnote markup: 

```
^ as you can clearly see on the image …
```

The thing is, to get this right – like optionally displaying notes on the slides or exporting it to a seperate file – a lot of logic comes into play. Best thing is probably to just wrap this in some custom class `<div>` and let the template assets do the rest.
