### ISSUE TITLE
Responsive on mobile in landscape mode

### ISSUE THREAD

**Issue by Bartvds** [jdan/cleaver#77]
The cleaver sideshows look really nice in a mobile device, especially in portrait mode the responsive design works well.

But the landscape view is less well:

I used a Samsung S3: with FireFox Mobile it is a bit crunched-up. 

On mobile Chrome the portrait mode works well too, but the landscape mode is a mess: the layout collapses and can't navigate (or it hangs.. not sure :): I seems as if the arrow-controls are behind the content?

**Comment by firstdoit** [comment]
Closing for amount of time without interaction.
