### ISSUE TITLE
Replace `cleaver watch` with `cleaver --live`

### ISSUE THREAD

**Issue by jdan** [jdan/cleaver#88]
I would like to phase out cleaver watch and opt-in for something a bit nicer. I'm thinking a `--live` option which does two things:

* automatically rebuilds with an associated file is changed (we could just check for js, css, md, and mustache)
* adds a live-reload functionality to the rendered slideshow

**Comment by juanbrujo** [comment]
+1 to this improvement

**Comment by sebie** [comment]
Yup, deffenitly a +1 (:+1:) to this.

**Comment by firstdoit** [comment]
Closing for amount of time without interaction.
